### ISSUE TITLE
Tornado Mixer throwing error on TOR browser: "Web assembly is not defined"

### ISSUE THREAD

**Issue by jjmr007** [peppersec/tornado-mixer#11]
I tried to obfuscate 0.1 kETH (in Kovan test network). I did my deposit using Brave browser, but I wanted to try a real life experience using TOR browser for the withdraw transaction.

On TOR browser it throws the "Web assembly is not defined" error, but when tried on Brave, "withdraw" successfully calculates the SNARK proof. Perhaps it is needed to [upgrade NodeJs](https://stackoverflow.com/questions/53871470/referenceerror-webassembly-is-not-defined) ?

Likely the same issue will happen on main net.
![TOR ERROR](https://user-images.githubusercontent.com/17028457/65478501-fbd3e600-de57-11e9-95a9-8ace1b3534f7.PNG)
![BRAVE SUCCESS](https://user-images.githubusercontent.com/17028457/65478537-2160ef80-de58-11e9-963e-211614bc5086.PNG)

**Comment by rstormsf** [comment]
@jjmr007 you have to enable WebAssembly 
Here is how: 
https://twitter.com/TornadoCash/status/1159555916284534785?s=19

**Comment by jjmr007** [comment]
Cool! successfully withdrawn!
