### ISSUE TITLE
e.returnValues.commitment.eq is not a function

### ISSUE THREAD

**Issue by techieanant** [peppersec/tornado-mixer#8]
Getting this error when running ./cli.js withdraw <note> <address>
![image](https://user-images.githubusercontent.com/7658579/63231582-dd345c80-c1d2-11e9-9268-e15079a1bea1.png)

**Comment by pertsev** [comment]
@techieanant  I cannot reproduce. Please describe your environment (looks like ubuntu, right?).

**Comment by n2nco** [comment]
I'm seeing that:

`console.log(e.returnValues.commitment.eq.toString())` 

outputs:

```
function (other) {
        return _bnify(this).eq(toBN(other));
    }
```

which maps to the ethers.js file: 

https://github.com/ethers-io/ethers.js/blob/master/src.ts/utils/bignumber.ts#L149

Recommendations: 
nvm use 11.15.0
delete & reinstall node modules.
